# Generated by Django 4.1.1 on 2022-10-07 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artikel',
            name='kategori',
        ),
        migrations.AddField(
            model_name='artikel',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.kategori'),
        ),
    ]
