# Generated by Django 4.1.3 on 2022-11-14 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_rename_host_artikel_kategori_artikel_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriArtikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategori', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='KategoriProduk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategori', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('harga', models.IntegerField(default=0, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('kategori_produk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.kategoriproduk')),
            ],
        ),
        migrations.RemoveField(
            model_name='artikel',
            name='kategori',
        ),
        migrations.DeleteModel(
            name='Kategori',
        ),
        migrations.AddField(
            model_name='artikel',
            name='kategori_artikel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.kategoriartikel'),
        ),
    ]
