# Generated by Django 4.1.3 on 2022-11-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_produk_harga'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategoriartikel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='kategoriproduk',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
