# Generated by Django 4.1.3 on 2022-11-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='gambar',
            field=models.ImageField(null=True, upload_to='images_produk/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='gambar',
            field=models.ImageField(null=True, upload_to='images_slider/'),
        ),
    ]
