# Generated by Django 4.1.3 on 2022-11-26 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_produk_gambar_alter_slider_gambar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produk',
            old_name='judul',
            new_name='nama_produk',
        ),
    ]
