# Generated by Django 4.1.3 on 2022-12-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_kategoriresep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('thumb', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('times', models.CharField(max_length=255)),
                ('serving', models.CharField(max_length=255)),
                ('difficulty', models.CharField(max_length=255)),
                ('author_user', models.CharField(max_length=255)),
                ('author_datePublished', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('ingredient', models.CharField(max_length=255)),
                ('step', models.CharField(max_length=255)),
                ('needItem_itemName', models.CharField(max_length=255)),
                ('needItem_thumbItem', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
