# Generated by Django 4.1.3 on 2022-12-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_resep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kategoriresep',
            old_name='judul',
            new_name='category',
        ),
        migrations.AddField(
            model_name='kategoriresep',
            name='key',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
