# Generated by Django 4.1.3 on 2022-12-16 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0013_rename_judul_kategoriresep_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resep',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resep',
            name='is_from_api',
            field=models.BooleanField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='kategori_resep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.kategoriresep'),
        ),
        migrations.AddField(
            model_name='resep',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='url_youtube',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resep',
            name='author_datePublished',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resep',
            name='author_user',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resep',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='resep',
            name='difficulty',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resep',
            name='ingredient',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resep',
            name='key',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resep',
            name='needItem_itemName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resep',
            name='needItem_thumbItem',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resep',
            name='serving',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resep',
            name='step',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resep',
            name='thumb',
            field=models.ImageField(null=True, upload_to='images_resep/'),
        ),
        migrations.AlterField(
            model_name='resep',
            name='times',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resep',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
