# Generated by Django 4.1.3 on 2022-12-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='images_slider/'),
        ),
    ]
