# Generated by Django 4.1.3 on 2022-12-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_artikel_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategoriartikel',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
