# Generated by Django 4.1.3 on 2022-12-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_kategoriartikel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='resep',
            name='is_acc',
            field=models.BooleanField(default=0, null=True),
        ),
    ]
