# Generated by Django 4.1.3 on 2022-12-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_resep_is_acc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resep',
            name='is_acc',
        ),
        migrations.AddField(
            model_name='resep',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
