# Generated by Django 4.1.3 on 2022-12-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_remove_resep_is_acc_resep_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
