# Generated by Django 4.1.3 on 2022-12-21 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_produk_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmarks',
            name='difficulty_resep',
        ),
        migrations.RemoveField(
            model_name='bookmarks',
            name='key_resep',
        ),
        migrations.RemoveField(
            model_name='bookmarks',
            name='serving_resep',
        ),
        migrations.RemoveField(
            model_name='bookmarks',
            name='thumb_resep',
        ),
        migrations.RemoveField(
            model_name='bookmarks',
            name='times_resep',
        ),
        migrations.RemoveField(
            model_name='bookmarks',
            name='title_resep',
        ),
        migrations.AddField(
            model_name='bookmarks',
            name='resep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.resep'),
        ),
        migrations.AlterField(
            model_name='resep',
            name='ingredient',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='resep',
            name='step',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='resep',
            name='thumb',
            field=models.ImageField(max_length=255, null=True, upload_to='images_resep/'),
        ),
    ]
